package org.proxmarkdesk.android;
import org.proxmarkdesk.android.capability.CliCompat;
import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.regex.*;

public final class CommandCatalog {
    public static final String VERSION="Iceman "+CliCompat.CURRENT_VERSION+" / Android ARM64";
    public static class Entry {
        public String command,original,description;public boolean offline;
        public String group(){String[] s=command.split(" ");return s.length>2?s[0]+" "+s[1]:s[0];}
        public String category(){String c=command.substring(command.lastIndexOf(' ')+1);if(c.matches(".*(sim|sniff).*"))return "Захват и эмуляция";if(c.matches(".*(write|wrbl|restore|wipe|format|setuid|setkey|changekey|clone|delete).*"))return "Запись и изменение";if(c.matches(".*(auth|key|pwd|chk|brute|nested|recover|crack|darkside|autopwn).*"))return "Ключи и аутентификация";if(c.matches(".*(dump|read|info|search|list|view|status|version).*"))return "Чтение и информация";return "Инструменты и настройки";}
        public String toString(){return command+"\n"+description;}
    }
    static final Map<String,String> actions=new HashMap<>();
    public static void loadRussian(InputStream in)throws IOException {try(BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){String line;while((line=r.readLine())!=null){String[] p=line.split("\t",2);if(p.length==2)actions.put(p[0],p[1]);}}}
    public static String russian(String command){String[] tokens=command.trim().split("\\s+");String verb=tokens.length==0?"":tokens[tokens.length-1];String action=actions.get(verb);if(action==null){for(int i=tokens.length-1;i>=0;i--)if(actions.containsKey(tokens[i])){action=actions.get(tokens[i]);break;}}if(action==null)action="Операция клиента «"+command+"»; параметры и назначение уточняются в справке Iceman";String scope=tokens.length>1?String.join(" ",Arrays.copyOf(tokens,tokens.length-1)):"Iceman";return action+" · "+scope;}
    public static List<Entry> parse(InputStream in)throws IOException {List<Entry> result=new ArrayList<>();try(BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){String line;Pattern p=Pattern.compile("^\\s*([a-z0-9_][a-z0-9_ .-]*?)\\s*\\|\\s*([YN])\\s*\\|(.*)$");while((line=r.readLine())!=null){Matcher m=p.matcher(line);if(!m.matches())continue;Entry e=new Entry();e.command=m.group(1).trim();e.offline=m.group(2).equals("Y");e.original=m.group(3).trim();e.description=russian(e.command);result.add(e);}}return result;}
    public static List<Entry> filter(List<Entry> entries,String query,String group,String category,Set<String> favorites,boolean onlyFavorites){String[] terms=query.toLowerCase(Locale.ROOT).trim().split("\\s+");List<Entry> result=new ArrayList<>();for(Entry e:entries){if(!group.isEmpty()&&!e.command.equals(group)&&!e.command.startsWith(group+" "))continue;if(!category.isEmpty()&&!category.equals(e.category()))continue;if(onlyFavorites&&!favorites.contains(e.command))continue;String text=(e.command+" "+e.description+" "+e.original).toLowerCase(Locale.ROOT);boolean match=true;for(String term:terms)if(!text.contains(term)){match=false;break;}if(match)result.add(e);}return result;}
    public static String familyPrefix(TagInfo tag){if(tag==null||!tag.detected||tag.ambiguous)return "";String s=tag.details.toLowerCase(Locale.ROOT);String[][] specific={{"ntag 424","hf ntag424"},{"mifare plus","hf mfp"},{"cipurse","hf cipurse"},{"st25ta","hf st25ta"},{"seos","hf seos"},{"lto-cm","hf lto"},{"thinfilm","hf thinfilm"},{"texkom","hf texkom"},{"xerox","hf xerox"},{"hitag","lf hitag"},{"indala","lf indala"},{"awid","lf awid"},{"ioprox","lf io"},{"fdx-b","lf fdxb"},{"nexwatch","lf nexwatch"},{"cotag","lf cotag"},{"keri","lf keri"},{"t55","lf t55xx"}};for(String[] p:specific)if(s.contains(p[0]))return p[1];String[] prefixes={"hf 14a","hf mf","hf mfu","hf 15","hf mfdes","lf em 410x","lf hid","lf t55xx","hf 14b","hf felica","hf iclass","hf legic","hf topaz",""};return tag.family>=0&&tag.family<prefixes.length?prefixes[tag.family]:"";}
}
