package org.proxmarkdesk.android;
import org.proxmarkdesk.android.capability.CliCompat;
import android.app.*;import android.content.*;import android.net.Uri;import android.os.*;import android.text.*;import android.view.*;import android.widget.*;
import java.io.*;import java.nio.file.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.*;import java.util.zip.*;import org.json.*;

/** Functional pages kept separate from transport and file parsers. */
public final class FeaturePages {
    final MainActivity a;final ExecutorService reader=Executors.newSingleThreadExecutor();Future<?> searchTask;int searchGeneration;List<CommandCatalog.Entry> entries;String catalogStamp="";
    FeaturePages(MainActivity activity){a=activity;}
    List<CommandCatalog.Entry> catalog(){try{File file=a.service==null?null:new File(a.service.library,"commands.txt");if(file!=null){File version=new File(a.service.library,"commands-client.txt");if(!version.isFile()||!new String(java.nio.file.Files.readAllBytes(version.toPath()),java.nio.charset.StandardCharsets.UTF_8).trim().equals(CliCompat.CURRENT_VERSION))file=null;}String stamp=file!=null&&file.isFile()?file.getAbsolutePath()+":"+file.lastModified():"asset";if(entries==null||!stamp.equals(catalogStamp)){CommandCatalog.loadRussian(a.getAssets().open("commands-ru.tsv"));entries=CommandCatalog.parse(file!=null&&file.isFile()?new FileInputStream(file):a.getAssets().open("commands.txt"));catalogStamp=stamp;}return entries;}catch(Exception e){a.message("Каталог: "+e.getMessage());return Collections.emptyList();}}
    LinearLayout plain(){LinearLayout box=new LinearLayout(a);box.setOrientation(1);box.setPadding(a.dp(10),a.dp(8),a.dp(10),0);a.body.addView(box,new LinearLayout.LayoutParams(-1,-1));return box;}
    void changed(EditText input,Runnable action){input.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int x,int c,int f){}public void onTextChanged(CharSequence s,int x,int b,int c){action.run();}public void afterTextChanged(Editable e){}});}
    void selected(Spinner spinner,Runnable action){spinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,View v,int i,long id){action.run();}});}
    Set<String> favorites(){return new HashSet<>(a.prefs().getStringSet("favorites",new HashSet<>()));}
    void commands(String prefix,String initial){LinearLayout box=plain();box.addView(a.text(prefix.isEmpty()?"Справочник команд":"Команды: "+prefix,20));if(prefix.isEmpty()){box.addView(a.text("Каталог встроенного Iceman "+CliCompat.CURRENT_VERSION+". Его можно повторно получить из клиента. Доступность команд зависит от устройства.",12));box.addView(a.button("Обновить каталог из клиента",()->{if(a.ready()){a.service.catalogue();a.page(3);}}));}commandList(box,prefix,initial);}
    void commandList(LinearLayout box,String prefix,String initial){
        List<CommandCatalog.Entry> all=catalog();EditText query=a.input(box,"Поиск: команда или русское описание",initial);TextView count=a.text("",12);box.addView(count);
        CheckBox favorite=a.themedCheckBox();favorite.setText("Только избранное");box.addView(favorite);
        Spinner categories=a.spinner(box,"Назначение",new String[]{"Все","Чтение и информация","Запись и изменение","Ключи и аутентификация","Захват и эмуляция","Инструменты и настройки"});
        ListView list=new ListView(a);box.addView(list,new LinearLayout.LayoutParams(-1,0,1));List<CommandCatalog.Entry> shown=new ArrayList<>();
        ArrayAdapter<String> adapter=a.darkAdapter(new ArrayList<>());list.setAdapter(adapter);
        Runnable filter=()->{shown.clear();shown.addAll(CommandCatalog.filter(all,query.getText().toString(),prefix,categories.getSelectedItemPosition()==0?"":categories.getSelectedItem().toString(),favorites(),favorite.isChecked()));adapter.clear();for(CommandCatalog.Entry e:shown)adapter.add(e.toString());count.setText("Найдено: "+shown.size()+" / "+all.size()+" · "+CommandCatalog.VERSION);};
        changed(query,filter);selected(categories,filter);favorite.setOnCheckedChangeListener((v,b)->filter.run());list.setOnItemClickListener((v,row,pos,id)->command(shown.get(pos)));filter.run();
    }
    void command(CommandCatalog.Entry e){Set<String> f=favorites();new AlertDialog.Builder(a).setTitle(e.command).setMessage(e.description+"\n\n"+e.original+"\n\n"+(e.offline?"Есть офлайн-режим. Некоторые параметры требуют устройства.":"Требуется устройство.")+" Поддержка конкретной меткой/прошивкой уточняется по справке и ответу клиента.").setPositiveButton("Параметры",(d,w)->parameters(e.command)).setNeutralButton(f.contains(e.command)?"Убрать из избранного":"В избранное",(d,w)->{if(!f.add(e.command))f.remove(e.command);a.prefs().edit().putStringSet("favorites",f).apply();}).setNegativeButton("Справка -h",(d,w)->{if(a.service!=null&&a.service.sessionState.isClientAlive())a.run(e.command+" -h",30);else a.message("Запустите офлайн-клиент или подключите устройство для встроенной справки. Русское описание доступно без подключения.");}).show();}
    void parameters(String command){LinearLayout box=new LinearLayout(a);box.setOrientation(1);EditText value=a.input(box,"Команда и параметры",command+" ");value.setSingleLine(true);new AlertDialog.Builder(a).setTitle("Параметры операции").setView(box).setPositiveButton("Выполнить",(d,w)->a.guard(()->a.run(value.getText().toString(),300))).setNeutralButton("В консоль",(d,w)->{a.prefs().edit().putString("draft",value.getText().toString()).apply();a.page(3);}).setNegativeButton("Отмена",null).show();}
    void read(){LinearLayout box=plain();LinearLayout buttons=new LinearLayout(a);String[] names={"Авто","Поиск HF","Поиск LF"},cmds={"auto","hf search","lf search"};for(int i=0;i<3;i++){String cmd=cmds[i];Button b=a.button(names[i],()->a.run(cmd,300));b.setEnabled(a.service==null||!a.service.sessionState.isBusy());buttons.addView(b,new LinearLayout.LayoutParams(0,-2,1));}box.addView(buttons);
        a.shownTagRevision=a.service==null?-1:a.service.sessionState.revision;TagInfo tag=a.service==null?null:a.service.tagInfo;
        if(a.service!=null&&a.service.sessionState.isBusy()){box.addView(a.text("Поиск / получение сведений… Команда выполняется до завершения.",14));}
        if(tag==null)return;
        if(!tag.detected||tag.ambiguous){box.addView(a.text(tag.summary(),14));box.addView(a.button("Выбрать семейство вручную",this::manualFamily));return;}
        box.addView(a.text((a.service.tagCached?"Из истории · текущим чтением не подтверждено\n":"")+tag.summary(),14));
        box.addView(a.button("Полные сведения",()->report("Карточка метки",tag.report())));
        box.addView(a.button("Действия для этой карты",()->a.page(15)));
        box.addView(a.button("Выбрать другое семейство",this::manualFamily));
        String prefix=CommandCatalog.familyPrefix(tag);if(prefix.isEmpty()){box.addView(a.text("Семейство требует ручного выбора; доступны все команды клиента.",13));}
        commandList(box,prefix,"");
    }
    void manualFamily(){SortedSet<String> groups=new TreeSet<>();for(CommandCatalog.Entry e:catalog())if(e.command.startsWith("hf ")||e.command.startsWith("lf "))groups.add(e.group());String[] values=groups.toArray(new String[0]);new AlertDialog.Builder(a).setTitle("Семейства HF / LF").setItems(values,(d,i)->{a.body.removeAllViews();commands(values[i],"");}).show();}
    void report(String title,String text){a.body.removeAllViews();LinearLayout box=a.content();box.addView(a.text(title,20));box.addView(a.button("Экспорт отчёта",()->a.export(text.getBytes(StandardCharsets.UTF_8),"report.txt")));box.addView(a.text(text,13));}
    void history(){LinearLayout box=plain();box.addView(a.text("История и результаты · кэш",20));EditText query=a.input(box,"Поиск: UID, команда, описание, текст результата","");TextView status=a.text("Чтение истории…",12);box.addView(status);ListView list=new ListView(a);box.addView(list,new LinearLayout.LayoutParams(-1,0,1));ArrayAdapter<String> adapter=a.darkAdapter(new ArrayList<>());list.setAdapter(adapter);List<JSONObject> results=new ArrayList<>();
        Runnable search=()->{int generation=++searchGeneration;if(searchTask!=null)searchTask.cancel(true);String q=query.getText().toString();if(a.service==null||a.service.cache==null)return;ResultCache cache=a.service.cache;searchTask=reader.submit(()->{try{List<JSONObject> found=cache.search(q);a.runOnUiThread(()->{if(generation!=searchGeneration||a.isDestroyed())return;results.clear();results.addAll(found);adapter.clear();for(JSONObject r:found)adapter.add(r.optString("command")+"\n"+r.optString("uid")+" · "+r.optString("device")+" · "+r.optString("status")+"\n"+new Date(r.optLong("started")));status.setText("Записей: "+found.size()+". Частичный вывод сохранён и при обрыве связи.");});}catch(Exception e){a.runOnUiThread(()->status.setText("Ошибка истории: "+e.getMessage()));}});};changed(query,search);list.setOnItemClickListener((p,v,i,id)->historyRecord(results.get(i)));search.run();}
    void historyRecord(JSONObject r){try{File f=a.service.cache.log(r);String text=r.toString(2)+"\n\n"+ResultCache.preview(f,240000);report("Результат операции",text);LinearLayout box=(LinearLayout)((ScrollView)a.body.getChildAt(0)).getChildAt(0);box.addView(a.button("Экспорт полного вывода",()->a.exportFile(f)));box.addView(a.button("Повторить с параметрами",()->parameters(r.optString("command"))));}catch(Exception e){a.message(e.getMessage());}}
    void storage(LinearLayout box){box.addView(a.text("Библиотека устройства",20));EditText profile=a.input(box,"Имя устройства / профиль",a.prefs().getString("deviceProfile","Proxmark3-Easy"));box.addView(a.button("Выбрать профиль устройства",()->a.guard(()->{try{a.service.selectProfile(profile.getText().toString());a.savedUid="";a.savedPassword="";a.page(0);}catch(Exception e){a.message(e.getMessage());}})));
        box.addView(a.button("Выбрать папку в Загрузках",()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION|Intent.FLAG_GRANT_PREFIX_URI_PERMISSION);a.startActivityForResult(i,31);}));
        CheckBox keys=a.themedCheckBox();keys.setText("Копировать папку паролей и ключей открытым текстом");keys.setChecked(a.prefs().getBoolean("mirrorPasswords",false));keys.setOnCheckedChangeListener((v,b)->a.prefs().edit().putBoolean("mirrorPasswords",b).apply());box.addView(keys);
        box.addView(a.text("Выберите доступную папку внутри Загрузок. Создаются ProxmarkDesk/<устройство>/Дампы, Трассы, Сигналы, Профили, Пароли, Журналы, Отчёты, Сценарии и Резервные копии. Журналы могут содержать введённые ключи. Оригиналы сначала сохраняются внутри приложения.",13));
        box.addView(a.button("Повторить копирование",()->{if(a.ready()){a.service.requestMirror();a.message("Копирование запрошено; результат показан в состоянии библиотеки.");}}));box.addView(a.button("Состояние библиотеки",()->a.message(a.service==null?"Служба запускается":a.service.storageStatus+"\n"+a.service.cacheError)));
        box.addView(a.button("Резервная копия всей библиотеки",()->backup()));
    }
    void backup(){if(a.service==null||a.service.sessionState.isBusy()){a.message("Дождитесь завершения операции");return;}File root=a.service.library;reader.submit(()->{try{File out=new File(a.getCacheDir(),"library-"+System.currentTimeMillis()+".zip");try(ZipOutputStream z=new ZipOutputStream(new FileOutputStream(out))){pack(root,root,z);}a.runOnUiThread(()->{if(!a.isDestroyed())a.exportFile(out);});}catch(Exception e){a.runOnUiThread(()->a.message(e.getMessage()));}});}
    static void pack(File root,File dir,ZipOutputStream z)throws Exception{File[] fs=dir.listFiles();if(fs!=null)for(File f:fs){if(f.isDirectory()){if(!f.getName().equals("emulation"))pack(root,f,z);}else if(!f.getName().endsWith(".tmp")){z.putNextEntry(new ZipEntry(root.toPath().relativize(f.toPath()).toString().replace('\\','/')));try(InputStream in=new FileInputStream(f)){byte[] b=new byte[16384];int n;while((n=in.read(b))!=-1)z.write(b,0,n);}z.closeEntry();}}}
    static final String[] TRACE_TYPES={"raw","14a","14b","15","7816","cryptorf","des","felica","ht1","ht2","hts","htu","iclass","legic","lto","mf","seos","thinfilm","topaz","mfp","fmcos20"};
    void trace(File f){new AlertDialog.Builder(a).setTitle("Протокол трассы (по файлу не гарантирован)").setItems(TRACE_TYPES,(d,i)->{try{if(a.service==null||!a.service.sessionState.isClientAlive())throw new IOException("Для декодирования запустите офлайн-клиент или подключите Proxmark3");a.service.viewTrace(f,TRACE_TYPES[i]);a.page(3);}catch(Exception e){a.message(e.getMessage());}}).show();}
    void signals(){LinearLayout box=a.content();box.addView(a.text("Сигналы и декодирование",20));box.addView(a.button("Получить LF-сигнал",()->a.actions.run("lf.read",120)));box.addView(a.button("Открыть сохранённый сигнал",()->a.page(4)));box.addView(a.button("Настройки выборки LF",()->parameters("lf config")));box.addView(a.button("Декодировать LF из буфера",()->a.actions.run("lf.search.buffer",120)));box.addView(a.button("Сохранить буфер сигнала",()->{Map<String,String> p=new HashMap<>();p.put("path","dumps/signal-"+System.currentTimeMillis());a.actions.run("data.save",p,120);}));for(String c:new String[]{"data rawdemod","data detectclock","data autocorr","data norm","data decimate","data ltrim","data rtrim","data hpf","data iir","data getbitstream"})box.addView(a.button(CommandCatalog.russian(c),()->parameters(c)));box.addView(a.button("Все инструменты обработки",()->{a.body.removeAllViews();commands("data","");}));}
    void scripts(){LinearLayout box=a.content();box.addView(a.text("Сохранённые последовательности команд",20));box.addView(a.button("Список встроенных Lua-скриптов",()->a.actions.run("lua.list",120)));box.addView(a.button("Запустить Lua с параметрами",()->parameters("script run")));EditText name=a.input(box,"Имя сценария","Мой сценарий");EditText lines=a.themedEditText();lines.setHint("Команды Iceman: одна на строку");lines.setMinLines(5);lines.setGravity(Gravity.TOP);box.addView(lines);Spinner policy=a.spinner(box,"При предупреждении или ошибке",new String[]{"Остановить цепочку","Продолжить после предупреждения клиента"});box.addView(a.button("Сохранить сценарий",()->{try{File dir=new File(a.service.library,"scripts");dir.mkdirs();File f=new File(dir,LibraryMirror.profile(name.getText().toString())+".cmd");ResultCache.atomic(f,lines.getText().toString());a.service.requestMirror();a.page(11);}catch(Exception e){a.message(e.getMessage());}}));box.addView(a.button("Выполнить введённые команды",()->a.guard(()->{a.service.runSequence(lines.getText().toString(),policy.getSelectedItemPosition()==0);a.page(3);})));box.addView(a.text("Каждый шаг ожидает завершения предыдущего. Тайм-аут шага: 300 секунд. После обрыва соединения автоматического повтора нет. Внешние desktop-утилиты для Lua доступны не во всех Android-сценариях.",13));if(a.service!=null){File[] fs=new File(a.service.library,"scripts").listFiles((d,n)->n.endsWith(".cmd"));if(fs!=null)for(File f:fs)box.addView(a.button(f.getName(),()->{try{lines.setText(ResultCache.preview(f,60000));name.setText(f.getName().replaceFirst("\\.cmd$",""));}catch(Exception e){a.message(e.getMessage());}}));}}
    void close(){reader.shutdownNow();}
}

