package org.proxmarkdesk.android;
import android.app.*;import android.content.*;import android.widget.*;import java.io.*;import java.util.*;

public final class PythonPage {
    final MainActivity a;PythonPage(MainActivity a){this.a=a;}
    void show(){LinearLayout box=a.content();box.addView(a.text("Python · "+AndroidPython.VERSION,20));box.addView(a.text("Работает внутри APK без Termux. Файловые инструменты запускаются без Proxmark3; команды через pm3 используют подключение на вкладке Устройство. Результаты сохраняются в Журнале.",14));
        box.addView(a.button("Проверить встроенный Python",()->launch("python_selftest.py",false,"",120)));
        box.addView(a.button("Импортировать свой .py",()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.addCategory(Intent.CATEGORY_OPENABLE);a.startActivityForResult(i,32);}));
        box.addView(a.button("Остановить Python",()->{if(a.ready())a.service.cancelPython();}));
        box.addView(a.button("Сохранённые отчёты Python",()->{if(!a.ready())return;File[] files=new File(a.service.library,"reports").listFiles(File::isFile);if(files==null||files.length==0){a.message("Отчётов пока нет. Запустите опись дампов или отчёт об устройстве.");return;}Arrays.sort(files,(x,y)->Long.compare(y.lastModified(),x.lastModified()));String[] names=new String[files.length];for(int i=0;i<files.length;i++)names[i]=files[i].getName();new AlertDialog.Builder(a).setTitle("Экспорт отчёта").setItems(names,(d,i)->a.exportFile(files[i])).show();}));
        box.addView(a.button("Лицензии Python и библиотек",()->{try{String[] names=a.getAssets().list("python-licenses");new AlertDialog.Builder(a).setTitle("Лицензии").setItems(names,(d,i)->{try{a.features.report(names[i],new String(MainActivity.readStream(a.getAssets().open("python-licenses/"+names[i]),200000),java.nio.charset.StandardCharsets.UTF_8));}catch(Exception e){a.message(e.getMessage());}}).show();}catch(Exception e){a.message(e.getMessage());}}));
        box.addView(a.button("Справка и примеры",()->a.message("Встроенный Python поддерживает стандартную библиотеку и адаптер pm3.\n\nimport pm3\np = pm3.pm3()\np.console('hw version')\nprint(p.grabbed_output)\n\nРабочая папка — библиотека текущего устройства. Пути к дампам: dumps/имя.bin. Аргументы с пробелами заключайте в кавычки. input() показывает окно ввода.\n\nПолный нативный SWIG API, pip и сторонние пакеты не включены. Скрипты с такими зависимостями требуют адаптации. Пользовательский .py выполняется с доступом приложения к файлам и сети; root для Python не используется.")));
        EditText query=a.input(box,"Поиск скрипта или русского описания","");LinearLayout list=new LinearLayout(a);list.setOrientation(1);box.addView(list);
        Runnable update=()->{list.removeAllViews();String q=query.getText().toString().toLowerCase(Locale.ROOT);for(int i=0;i<AndroidPython.SCRIPTS.length;i++){String name=AndroidPython.SCRIPTS[i],desc=AndroidPython.DESCRIPTIONS[i];if((name+" "+desc).toLowerCase(Locale.ROOT).contains(q))list.addView(a.button(name+"\n"+desc,()->parameters(name,false,desc)));}if(a.service!=null){File[] files=new File(a.service.library,"scripts/python").listFiles((d,n)->n.endsWith(".py"));if(files!=null){Arrays.sort(files);for(File file:files)if(file.getName().toLowerCase(Locale.ROOT).contains(q))list.addView(a.button(file.getName()+" · пользовательский",()->parameters(file.getName(),true,"Импортированный скрипт")));}}};a.features.changed(query,update);update.run();
    }
    void parameters(String name,boolean custom,String description){LinearLayout box=new LinearLayout(a);box.setOrientation(1);box.addView(a.text(description,14));if(!custom)box.addView(a.text("Пример: "+AndroidPython.example(name),13));EditText args=a.input(box,"Аргументы (без имени скрипта)","");EditText seconds=a.input(box,"Максимальное время, секунд","300");seconds.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);
        box.addView(a.button("Добавить путь к дампу",()->{if(a.service==null)return;File[] files=a.service.dumps.listFiles(File::isFile);if(files==null||files.length==0){a.message("В библиотеке нет дампов");return;}Arrays.sort(files);String[] names=new String[files.length];for(int i=0;i<files.length;i++)names[i]=files[i].getName();new AlertDialog.Builder(a).setTitle("Выбрать файл").setItems(names,(d,i)->{String value="dumps/"+names[i];if(value.contains("\"")){a.message("Переименуйте файл: имя содержит кавычку");return;}args.append((args.length()>0?" ":"")+"\""+value+"\"");}).show();}));
        new AlertDialog.Builder(a).setTitle(name).setView(box).setPositiveButton("Запустить",(d,w)->a.guard(()->launch(name,custom,args.getText().toString(),Integer.parseInt(seconds.getText().toString())))).setNeutralButton("Просмотреть код",(d,w)->{if(!a.ready())return;final File library=a.service.library;a.features.reader.submit(()->{try{AndroidPython.install(a);File f=AndroidPython.script(a,library,name,custom);String source=ResultCache.preview(f,150000);a.runOnUiThread(()->{if(!a.isDestroyed())a.features.report(name,source);});}catch(Exception e){a.runOnUiThread(()->{if(!a.isDestroyed())a.message(e.getMessage());});}});}).setNegativeButton("Отмена",null).show();
    }
    void launch(String name,boolean custom,String args,int seconds){if(!a.ready())return;a.startForegroundService(new Intent(a,ClientService.class));a.service.runPython(name,custom,args,seconds);a.page(3);}
}
