package org.proxmarkdesk.android;
import org.proxmarkdesk.android.capability.CliCompat;
import android.app.*;import android.widget.*;import java.io.*;import java.util.*;import org.json.*;
import org.proxmarkdesk.android.capability.ActionDef;
import org.proxmarkdesk.android.capability.ActionRegistry;
import org.proxmarkdesk.android.capability.CardCapability;
/** Single scrolling reading screen and a common catalogue of commands and scripts. */
public final class ReadingPage {
 final MainActivity a;JSONObject manifest;String manual="";ReadingPage(MainActivity a){this.a=a;}
 JSONObject manifest()throws Exception{if(manifest==null)manifest=new JSONObject(new String(MainActivity.readStream(a.getAssets().open("resource-manifest.json"),2*1024*1024),java.nio.charset.StandardCharsets.UTF_8));return manifest;}
 void show(boolean full){try{
  TagInfo tag=a.service==null?null:a.service.tagInfo;a.shownTagRevision=a.service==null?-1:a.service.sessionState.revision;
  LinearLayout shell=new LinearLayout(a);shell.setOrientation(1);a.body.addView(shell,new LinearLayout.LayoutParams(-1,-1));ListView list=new ListView(a);shell.addView(list,new LinearLayout.LayoutParams(-1,-1));LinearLayout head=new LinearLayout(a);head.setOrientation(1);head.setPadding(a.dp(10),a.dp(6),a.dp(10),a.dp(6));list.addHeaderView(head,null,false);list.setAdapter(a.darkAdapter(new ArrayList<String>()));
  if(!full){if(a.service==null||!a.service.sessionState.isClientAlive()){head.addView(a.text("Proxmark3 не готов. Подключение настраивается отдельно от состояния карты.",14));head.addView(a.button("Подключение / устройство",()->a.page(0)));}LinearLayout row=new LinearLayout(a);String[] names={"Авто","Поиск HF","Поиск LF"},actions={"tag.auto","hf.search","lf.search"};for(int i=0;i<names.length;i++){String actionId=actions[i];Button b=a.button(names[i],()->{manual="";a.guard(()->a.actions.run(actionId,300));});b.setEnabled(a.service==null||!a.service.sessionState.isBusy());row.addView(b,new LinearLayout.LayoutParams(0,-2,1));}head.addView(row);
   if(a.service!=null&&a.service.sessionState.isBusy()){head.addView(a.text("Поиск и получение сведений… Команда выполняется до завершения.",14));return;}
   if(tag==null&&manual.isEmpty())return;
   if(tag!=null)head.addView(a.text((a.service.tagCached?"Из истории — метка сейчас не подтверждена\n":"")+tag.summary(),14));
   if(tag!=null&&tag.detected&&!tag.ambiguous){
    head.addView(a.button("Полные сведения",()->a.features.report("Карточка метки",tag.report())));
    CardCapability cap=a.service.currentCapability==null?CardCapability.UNKNOWN:a.service.currentCapability;
    List<ActionDef> contextual=ActionRegistry.forCardMenu(cap);
    String type=cap.subtype==null||cap.subtype.isEmpty()?TagInfo.FAMILIES[tag.family]:cap.subtype;
    head.addView(a.text("Меню для: "+type+" · действий: "+contextual.size(),14));
    if(contextual.isEmpty()) head.addView(a.text("Для этого точного типа пока доступны только сведения. Полный каталог Iceman находится в «Инструменты».",13));
    else head.addView(a.button("Действия для этой карты",()->a.page(15)));
    return;
   }
   head.addView(a.button("Уточнить семейство вручную",()->chooseFamily()));
   if((tag==null||!tag.detected||tag.ambiguous)&&manual.isEmpty()){head.addView(a.text("Нет однозначного определения: выберите семейство вручную или повторите поиск.",14));return;}
   if(manual.isEmpty()&&CommandCatalog.familyPrefix(tag).isEmpty()){head.addView(a.text("Для этого результата нет точного соответствия. Выберите семейство вручную; весь каталог не выдаётся за подходящий.",14));return;}
  }else{
   head.addView(a.text("Команды и скрипты",21));head.addView(a.button("Обновить команды из клиента",()->{if(a.ready()){a.service.catalogue();a.page(3);}}));
   head.addView(a.button("Lua: диагностика и библиотеки",this::environment));head.addView(a.button("Командные файлы .cmd",()->inventory("cmdscripts/")));head.addView(a.button("Сохранённые последовательности команд",()->a.page(11)));
  }
  if(!manual.isEmpty()&&!full)head.addView(a.text("Ручной выбор: "+manual+". Совместимость с меткой не подтверждена.",13));
  List<ReadingActions.Action> all=ReadingActions.all(a.features.catalog(),manifest());EditText query=a.input(head,"Поиск команды, скрипта или русского описания","");Spinner kinds=a.spinner(head,"Показать",new String[]{"Все","Команда","Lua","Python"});CheckBox special=a.themedCheckBox();special.setText(full?"Все действия доступны в каталоге":"Показать специальные варианты с дополнительными условиями");special.setChecked(full);special.setEnabled(!full);if(full){special.setTextColor(a.DISABLED);special.setAlpha(1f);}head.addView(special);CheckBox favorite=a.themedCheckBox();favorite.setText("Только избранное");head.addView(favorite);TextView count=a.text("",12);head.addView(count);List<ReadingActions.Action> visible=new ArrayList<>();ArrayAdapter<String> adapter=a.darkAdapter(new ArrayList<>());list.setAdapter(adapter);
  Runnable filter=()->{visible.clear();visible.addAll(ReadingActions.filter(all,tag,manual,full,query.getText().toString(),kinds.getSelectedItem().toString(),special.isChecked()));if(favorite.isChecked())visible.removeIf(item->!a.features.favorites().contains(item.name));adapter.clear();for(ReadingActions.Action item:visible)adapter.add(item.label());count.setText("Действий: "+visible.size()+" · Iceman "+CliCompat.CURRENT_VERSION+"\nПодбор по семейству не заменяет проверку модели и условий.");};a.features.changed(query,filter);a.features.selected(kinds,filter);special.setOnCheckedChangeListener((v,b)->filter.run());favorite.setOnCheckedChangeListener((v,b)->filter.run());list.setOnItemClickListener((v,row,pos,id)->{int index=pos-list.getHeaderViewsCount();if(index>=0&&index<visible.size())details(visible.get(index));});filter.run();
 }catch(Exception e){a.message("Каталог: "+e.getMessage());}}
 void chooseFamily(){SortedSet<String> groups=new TreeSet<>();for(CommandCatalog.Entry e:a.features.catalog())if(e.command.startsWith("hf ")||e.command.startsWith("lf ")){String g=e.group();if(e.command.startsWith("lf em ")){String[] parts=e.command.split(" ");if(parts.length>=4)g="lf em "+parts[2];}groups.add(g);}String[] names=groups.toArray(new String[0]);new AlertDialog.Builder(a).setTitle("Ручной выбор семейства").setItems(names,(d,i)->{manual=names[i];a.page(1);}).show();}
 void details(ReadingActions.Action item){String text=item.description+"\n\nТребования: "+item.requirements+"\n"+(item.condition.isEmpty()?"":"Особая модель/формат: "+item.condition+"\n")+String.join("\n",item.constraints)+(item.missing.isEmpty()?"":"\nНе найдены модули: "+String.join(", ",item.missing))+"\n\nПроверка: "+item.validation+(item.usage.isEmpty()?"":"\n\nСправка из исходника:\n"+item.usage);
  LinearLayout extra=new LinearLayout(a);extra.setOrientation(1);Button star=a.button(a.features.favorites().contains(item.name)?"Убрать из избранного":"В избранное",()->{Set<String> f=a.features.favorites();if(!f.add(item.name))f.remove(item.name);a.prefs().edit().putStringSet("favorites",f).apply();});star.setOnClickListener(v->{Set<String> f=a.features.favorites();if(!f.add(item.name))f.remove(item.name);a.prefs().edit().putStringSet("favorites",f).apply();star.setText(f.contains(item.name)?"Убрать из избранного":"В избранное");});extra.addView(star);
  new AlertDialog.Builder(a).setView(extra).setTitle(item.kind+" · "+item.name).setMessage(text).setPositiveButton("Параметры",(d,w)->{if(!item.missing.isEmpty()){a.message("Сначала восстановите зависимости Lua");return;}if(item.kind.equals("Python")){a.pythonPage.parameters(item.name,false,item.description);return;}if(item.kind.equals("Команда")){a.features.parameters(item.name);return;}luaParameters(item);}).setNeutralButton(item.kind.equals("Команда")?"Справка -h":"Исходный код",(d,w)->{if(item.kind.equals("Команда")){a.run(item.name+" -h",30);return;}if(item.kind.equals("Python")){a.pythonPage.parameters(item.name,false,item.description);return;}source(item.file);}).setNegativeButton("Закрыть",null).show();
 }
 void luaParameters(ReadingActions.Action item){LinearLayout box=new LinearLayout(a);box.setOrientation(1);box.addView(a.text(item.description+(item.condition.isEmpty()?"":"\nУсловие: "+item.condition)+"\n"+String.join("\n",item.constraints),14));EditText args=a.input(box,"Аргументы Lua (справка выше)","");EditText timeout=a.input(box,"Максимальное время, секунд","300");timeout.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);new AlertDialog.Builder(a).setTitle(item.name).setView(box).setPositiveButton("Запустить",(d,w)->a.guard(()->{int seconds=Integer.parseInt(timeout.getText().toString());if(seconds<1||seconds>86400)throw new IllegalArgumentException("Время: 1–86400 секунд");String path=item.file.substring("luascripts/".length()).replaceFirst("\\.lua$","");a.run("script run "+path+(args.length()>0?" "+args.getText():""),seconds);})).setNegativeButton("Отмена",null).show();}
 void source(String path){if(!a.ready())return;final File root=new File(a.getFilesDir(),".proxmark3");a.features.reader.submit(()->{try{String value=ResultCache.preview(ResourceInstaller.child(root,path),180000);a.runOnUiThread(()->{if(!a.isDestroyed())a.features.report(path,value);});}catch(Exception e){a.runOnUiThread(()->a.message("Файл: "+e.getMessage()));}});}
 void environment(){LinearLayout box=new LinearLayout(a);box.setOrientation(1);box.addView(a.text(a.service==null?"Служба запускается":a.service.luaEnvironment,13));box.addView(a.button("Проверить / восстановить ресурсы",()->{if(a.ready()){a.service.repairResources();a.page(3);}}));box.addView(a.button("Проверить загрузку Lua без RF-операций",()->a.actions.run("lua.envcheck",45)));box.addView(a.button("Lua libraries",()->inventory("lualibs/")));box.addView(a.button("Lua scripts",()->inventory("luascripts/")));new AlertDialog.Builder(a).setTitle("Окружение Lua").setView(box).setPositiveButton("Закрыть",null).show();}
 void inventory(String prefix){try{JSONObject files=manifest().getJSONObject("files");List<String> paths=new ArrayList<>();for(Iterator<String> it=files.keys();it.hasNext();){String p=it.next();if(p.startsWith(prefix))paths.add(p);}Collections.sort(paths);new AlertDialog.Builder(a).setTitle(prefix+" · "+paths.size()).setItems(paths.toArray(new String[0]),(d,i)->{String p=paths.get(i);if(prefix.equals("cmdscripts/")){new AlertDialog.Builder(a).setTitle(p).setItems(new String[]{"Посмотреть файл","Запуск с параметрами"},(dialog,k)->{if(k==0)source(p);else a.features.parameters("script run "+p.substring(prefix.length()));}).show();}else source(p);}).show();}catch(Exception e){a.message(e.getMessage());}}
}

