package org.proxmarkdesk.android;
import java.util.*;import java.util.regex.*;import org.json.*;
/** Shared selection rules for reading, full catalogue, and host tests. */
public final class ReadingActions {
 public static class Action {public String name,kind,description,group="",condition="",usage="",file="",requirements="",validation="На устройстве не проверено";public boolean fileOnly;public List<String> constraints=new ArrayList<>();public List<String> missing=new ArrayList<>();public CommandCatalog.Entry command; public String label(){return kind+" · "+name+"\n"+description+(condition.isEmpty()?"":"\nУсловие: "+condition)+(constraints.isEmpty()?"":"\nТребуется проверка совместимости Android");}}
 public static List<Action> all(List<CommandCatalog.Entry> commands,JSONObject manifest)throws Exception{
  List<Action> list=new ArrayList<>();for(CommandCatalog.Entry e:commands){Action a=new Action();a.name=e.command;a.kind="Команда";a.group=e.group();a.description=e.description;a.command=e;a.requirements=e.offline?"Офлайн-клиент; некоторые параметры требуют устройства":"Подключённое устройство";String last=e.command.substring(e.command.lastIndexOf(' ')+1);if(e.command.startsWith("hf mf ")&&last.matches("c(get|set|load|save|wipe).*|gdm.*|gen[234].*"))a.condition="Magic";if(e.command.startsWith("hf mfu ")&&last.equals("setuid"))a.condition="Magic";list.add(a);}
  JSONArray scripts=manifest.getJSONArray("scripts");for(int i=0;i<scripts.length();i++){JSONObject s=scripts.getJSONObject(i);Action a=new Action();a.name=s.getString("name");a.file=s.getString("id");a.kind="Lua";a.group=s.optString("group");a.description=s.getString("description");a.condition=s.optString("condition");a.usage=s.optString("usage");a.fileOnly=s.optBoolean("fileOnly");a.requirements=a.fileOnly?"Файл дампа и офлайн-клиент":"Проверьте наличие метки и требования скрипта";a.validation=s.optString("tested");for(int j=0;j<s.getJSONArray("constraints").length();j++)a.constraints.add(s.getJSONArray("constraints").getString(j));for(int j=0;j<s.getJSONArray("missing").length();j++)a.missing.add(s.getJSONArray("missing").getString(j));if(a.name.startsWith("hf_ntag_")||a.name.startsWith("ntag_")){if(a.condition.isEmpty())a.condition="NTAG";}list.add(a);}
  for(int i=0;i<AndroidPython.SCRIPTS.length;i++){Action a=new Action();a.kind="Python";a.name=AndroidPython.SCRIPTS[i];a.description=AndroidPython.DESCRIPTIONS[i];a.fileOnly=true;a.requirements="Среда Python приложения; путь к файлу при необходимости";if(a.name.equals("pm3_mfd2eml.py")||a.name.equals("pm3_eml2mfd.py"))a.group="hf mf";a.validation="Логика проверена на компьютере; на Android не проверено";list.add(a);}return list;
 }
 public static boolean confirmed(TagInfo tag,String condition){if(condition.isEmpty())return true;if(tag==null)return false;String details=tag.details.toLowerCase(Locale.ROOT);if(condition.equals("NTAG"))return Pattern.compile("(?im)^.*(?:type:|type\\s*\\.\\.+)\\s*ntag\\s*[0-9]").matcher(details).find();if(condition.equals("Ultra/UL-5"))return Pattern.compile("\\bultra\\b|\\bul-?5\\b").matcher(details).find();return Pattern.compile("(?i)(?<![a-z0-9])"+Pattern.quote(condition)+"(?![a-z0-9])").matcher(details).find();}
 public static boolean family(Action a,TagInfo tag,String manual){String group=manual.isEmpty()?CommandCatalog.familyPrefix(tag):manual;if(group.isEmpty())return false;if(a.group.equals(group)||a.name.startsWith(group+" "))return true;return a.kind.equals("Команда")&&a.group.equals("hf 14a")&&Arrays.asList("hf mf","hf mfu","hf mfdes","hf mfp","hf ntag424").contains(group);}
 public static List<Action> filter(List<Action> all,TagInfo tag,String manual,boolean full,String query,String kind,boolean special){List<Action> out=new ArrayList<>();String[] words=query.toLowerCase(Locale.ROOT).trim().split("\\s+");for(Action a:all){if(!full&&(!family(a,tag,manual)||(!special&&(!confirmed(tag,a.condition)||!a.constraints.isEmpty()||!a.missing.isEmpty()))))continue;if(!kind.equals("Все")&&!kind.equals(a.kind))continue;String text=(a.name+" "+a.description+" "+a.group+" "+a.condition).toLowerCase(Locale.ROOT);boolean match=true;for(String word:words)if(!text.contains(word))match=false;if(match)out.add(a);}return out;}
}
