package org.proxmarkdesk.android;
import java.io.*;import java.nio.file.*;import java.security.*;import java.util.*;import java.util.zip.*;import org.json.*;
/** Installs a matched resource set, preserving custom files and backing up changed stock files. */
public final class ResourceInstaller {
 public static String hash(File f)throws Exception{MessageDigest md=MessageDigest.getInstance("SHA-256");try(InputStream in=new FileInputStream(f)){byte[] b=new byte[16384];int n;while((n=in.read(b))>0)md.update(b,0,n);}StringBuilder out=new StringBuilder();for(byte b:md.digest())out.append(String.format(Locale.ROOT,"%02x",b&255));return out.toString();}
 static File child(File root,String name)throws IOException{File f=new File(root,name);if(name.startsWith("/")||name.contains("\\")||!f.getCanonicalPath().startsWith(root.getCanonicalPath()+File.separator))throw new IOException("Недопустимый путь ресурса: "+name);return f;}
 public static String verify(JSONObject manifest,File root)throws Exception{
  JSONObject files=manifest.getJSONObject("files");int libs=0,scripts=0,cmds=0,missing=0,changed=0;StringBuilder problems=new StringBuilder();
  for(Iterator<String> i=files.keys();i.hasNext();){String name=i.next();if(name.startsWith("lualibs/"))libs++;if(name.startsWith("luascripts/"))scripts++;if(name.startsWith("cmdscripts/"))cmds++;File f=child(root,name);if(!f.isFile()){missing++;problems.append("Отсутствует: ").append(name).append('\n');}else if(!hash(f).equals(files.getString(name))){changed++;problems.append("Изменён: ").append(name).append('\n');}}
  return manifest.getString("client")+"\nResource files "+(missing==0&&changed==0?"OK":"FAILED")+"\nLua scripts: "+scripts+"\nLua libraries: "+libs+"\nCmd scripts: "+cmds+"\nMissing files: "+missing+"\nModified files: "+changed+"\n"+problems+"\nПроверена целостность файлов. Это не проверка выполнения на устройстве.";
 }
 public static String install(InputStream archive,JSONObject manifest,File root,File backupRoot)throws Exception{
  root.mkdirs();JSONObject expected=manifest.getJSONObject("files");Set<String> seen=new HashSet<>();int copied=0,backups=0;File backup=new File(backupRoot,System.currentTimeMillis()+"-"+UUID.randomUUID());
  try(ZipInputStream zip=new ZipInputStream(archive)){ZipEntry entry;byte[] b=new byte[16384];while((entry=zip.getNextEntry())!=null){String name=entry.getName();File target=child(root,name);if(entry.isDirectory())continue;if(!expected.has(name))throw new IOException("Неожиданный файл архива: "+name);if(!seen.add(name))throw new IOException("Повтор ресурса: "+name);String wanted=expected.getString(name);if(target.isFile()&&hash(target).equals(wanted))continue;target.getParentFile().mkdirs();File temp=File.createTempFile("resource-",".tmp",target.getParentFile());try{try(FileOutputStream out=new FileOutputStream(temp)){int n;while((n=zip.read(b))>0)out.write(b,0,n);out.getFD().sync();}if(!hash(temp).equals(wanted))throw new IOException("Контрольная сумма ресурса не совпала: "+name);if(target.exists()){File old=child(backup,name);old.getParentFile().mkdirs();Files.copy(target.toPath(),old.toPath());backups++;}try{Files.move(temp.toPath(),target.toPath(),StandardCopyOption.REPLACE_EXISTING,StandardCopyOption.ATOMIC_MOVE);}catch(AtomicMoveNotSupportedException e){Files.move(temp.toPath(),target.toPath(),StandardCopyOption.REPLACE_EXISTING);}copied++;}finally{Files.deleteIfExists(temp.toPath());}}}
  if(seen.size()!=expected.length())throw new IOException("Неполный архив ресурсов");String report=verify(manifest,root);if(!report.contains("Resource files OK"))throw new IOException(report);ResultCache.atomic(new File(root,"pmdesk-resource-version.json"),new JSONObject().put("id",manifest.getString("id")).put("client",manifest.getString("client")).toString());return report+"\nУстановлено/восстановлено: "+copied+"\nРезервных копий: "+backups+(backups>0?"\nПапка копий: "+backup.getAbsolutePath():"");
 }
}
